Document: shoppinglist
Title: Debian shoppinglist Manual
Author: <insert document author here>
Abstract: This manual describes what shoppinglist is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shoppinglist/shoppinglist.sgml.gz

Format: postscript
Files: /usr/share/doc/shoppinglist/shoppinglist.ps.gz

Format: text
Files: /usr/share/doc/shoppinglist/shoppinglist.text.gz

Format: HTML
Index: /usr/share/doc/shoppinglist/html/index.html
Files: /usr/share/doc/shoppinglist/html/*.html

  
